import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';

const posts = [
  { day: 'TODAY · 18:30', title: 'Self-cleaning kitchen counter', type: 'Reel', status: 'Ready' },
  { day: 'TOMORROW · 18:30', title: 'A window that generates clean water', type: 'Video', status: 'Review' },
  { day: 'SUN · 18:30', title: 'The desk that charges everything', type: 'Reel', status: 'Ready' },
];

export default function Home() {
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
    <View style={s.header}><View><Text style={s.eyebrow}>CONTENTGEN</Text><Text style={s.title}>Content Autopilot</Text></View><View style={s.avatar}><Text style={s.avatarText}>CG</Text></View></View>
    <View style={s.hero}>
      <View style={s.row}><View><Text style={s.heroLabel}>AUTOPILOT</Text><Text style={s.heroTitle}>Running</Text></View><Switch value trackColor={{true:'#7CFF6B'}} thumbColor="#fff" /></View>
      <Text style={s.muted}>Your next 14 posts are being prepared automatically.</Text>
      <View style={s.divider}/><View style={s.stats}><Stat n="2" l="Platforms"/><Stat n="1×" l="Daily"/><Stat n="18:30" l="Publish"/><Stat n="14" l="Ahead"/></View>
    </View>
    <Text style={s.section}>CHANNELS</Text><View style={s.channels}><Chip icon="logo-instagram" label="Instagram"/><Chip icon="logo-tiktok" label="TikTok"/></View>
    <View style={s.topic}><Text style={s.topicLabel}>CONTENT DIRECTION</Text><Text style={s.topicTitle}>Future Inventions</Text><Text style={s.muted}>Futuristic inventions that solve everyday problems · English</Text></View>
    <View style={s.sectionRow}><Text style={s.section}>UP NEXT</Text><Text style={s.link}>View calendar</Text></View>
    {posts.map((p,i)=><View style={s.post} key={p.title}><View style={s.number}><Text style={s.numberText}>{i+1}</Text></View><View style={{flex:1}}><Text style={s.postDay}>{p.day}</Text><Text style={s.postTitle}>{p.title}</Text><Text style={s.postMeta}>{p.type} · {p.status}</Text></View><Ionicons name="chevron-forward" color="#777" size={20}/></View>)}
    <TouchableOpacity style={s.button}><Ionicons name="sparkles" size={18}/><Text style={s.buttonText}>Generate more content</Text></TouchableOpacity>
    <View style={s.nav}>{[['home','Home'],['sparkles','Create'],['calendar','Calendar'],['albums','Library'],['settings','Settings']].map(([icon,label])=><View style={s.navItem} key={label}><Ionicons name={icon as any} size={21} color={label==='Home'?'#7CFF6B':'#777'}/><Text style={[s.navText,label==='Home'&&{color:'#7CFF6B'}]}>{label}</Text></View>)}</View>
  </ScrollView></SafeAreaView>;
}
function Stat({n,l}:{n:string,l:string}){return <View><Text style={s.statN}>{n}</Text><Text style={s.statL}>{l}</Text></View>}
function Chip({icon,label}:{icon:any,label:string}){return <View style={s.chip}><Ionicons name={icon} size={19} color="#fff"/><Text style={s.chipText}>{label}</Text><View style={s.dot}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#08090B'},page:{padding:20,paddingBottom:110},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},eyebrow:{color:'#7CFF6B',fontWeight:'900',letterSpacing:2,fontSize:12},title:{color:'#fff',fontSize:30,fontWeight:'800',marginTop:3},avatar:{width:42,height:42,borderRadius:21,backgroundColor:'#202226',alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'800'},hero:{backgroundColor:'#15171A',borderRadius:24,padding:20,borderWidth:1,borderColor:'#282B30'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},heroLabel:{color:'#7CFF6B',fontWeight:'800',fontSize:12,letterSpacing:1.5},heroTitle:{color:'#fff',fontSize:27,fontWeight:'800',marginVertical:3},muted:{color:'#92979F',lineHeight:20},divider:{height:1,backgroundColor:'#292C31',marginVertical:18},stats:{flexDirection:'row',justifyContent:'space-between'},statN:{color:'#fff',fontSize:17,fontWeight:'800'},statL:{color:'#777D85',fontSize:11,marginTop:3},section:{color:'#A7ABB2',fontSize:12,fontWeight:'800',letterSpacing:1.3,marginTop:24,marginBottom:10},channels:{flexDirection:'row',gap:10},chip:{flex:1,backgroundColor:'#15171A',borderRadius:16,padding:15,flexDirection:'row',gap:9,alignItems:'center',borderWidth:1,borderColor:'#282B30'},chipText:{color:'#fff',fontWeight:'700',flex:1},dot:{width:8,height:8,borderRadius:4,backgroundColor:'#7CFF6B'},topic:{backgroundColor:'#111316',borderRadius:20,padding:18,marginTop:20},topicLabel:{color:'#777D85',fontSize:11,fontWeight:'800',letterSpacing:1.2},topicTitle:{color:'#fff',fontSize:20,fontWeight:'800',marginVertical:5},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},link:{color:'#7CFF6B',fontWeight:'700',marginTop:14},post:{backgroundColor:'#111316',borderRadius:18,padding:14,marginBottom:10,flexDirection:'row',alignItems:'center',gap:12},number:{width:42,height:52,borderRadius:13,backgroundColor:'#202329',alignItems:'center',justifyContent:'center'},numberText:{color:'#7CFF6B',fontSize:18,fontWeight:'900'},postDay:{color:'#777D85',fontSize:10,fontWeight:'800'},postTitle:{color:'#fff',fontSize:15,fontWeight:'700',marginVertical:3},postMeta:{color:'#92979F',fontSize:12},button:{backgroundColor:'#7CFF6B',borderRadius:18,padding:17,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8,marginTop:10},buttonText:{fontWeight:'900',fontSize:15},nav:{position:'absolute',left:0,right:0,bottom:0,backgroundColor:'#0D0E10',borderTopWidth:1,borderTopColor:'#23252A',paddingVertical:11,flexDirection:'row',justifyContent:'space-around'},navItem:{alignItems:'center',gap:3},navText:{color:'#777',fontSize:10,fontWeight:'600'}});
